inherit_from:
  - https://raw.githubusercontent.com/ManageIQ/manageiq-style/master/.rubocop_base.yml
  - https://raw.githubusercontent.com/ManageIQ/manageiq-style/master/.rubocop_cc.yml
  - https://raw.githubusercontent.com/ManageIQ/manageiq-style/master/.rubocop_cc_base.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'spec/manageiq/**/*'
    - 'spec/tools/**/*'
    - 'vendor/**/*'

